language: python

python:
    - "2.6"
    - "2.7"

before_script:
    - sudo apt-get install mpich2
    - sudo apt-get install python-mpi4py

script:
    python setup.py build

install:
    python setup.py install
